include:
  - template: Security/SAST.gitlab-ci.yml

stages:
  - test
  - build
  - deploy

test project:
  stage: test
  image: node:16
  script:
    - yarn install
    - yarn test

build project:
  stage: build
  image: node:16
  script:
    - yarn install
    - yarn build
  artifacts:
    paths:
      - build/

# important to start/put netlify accounts in gitlab variables
netlify:
  stage: deploy
  image: node:16
  script:
    - npm install -g netlify-cli
    - netlify deploy --dir=build --prod
